### ISSUE TITLE
Atmosphere mechanics

### ISSUE THREAD

**Issue by JamesHinshelwood** [LimaInc/SustainableCraft#12]

**Comment by adam-kucz** [comment]
Atmosphere color determined by dominant gas. Gas amounts exactly follow amounts of bacteria for now. GetGasProgress(Gas) returns a value in [0.0f,1.0f] which is the amount of given gas in the atmosphere divided by a predetermined amount required to fill the bar completely.

TODO: sky color mixing, more interesting mechanics (pressure, temperature, etc.), more interesting progress bars (e.g. gas proportions balancing)
