### ISSUE TITLE
[DISCUSSION] Block type

### ISSUE THREAD

**Issue by JamesHinshelwood** [LimaInc/SustainableCraft#22]
Struggling to think about how to implement a neat method of having an abstract block type or if it is even needed.

At the moment, we just use an array of bytes, which is obviously bad. We should have an array of Block objects maybe?, and we can inherit different types of block from Block, eg. class Grass : Block. However, don't we want Blocks to be a struct, since they should be a value type? Or shouldn't they? C# lets you define structs which implement interfaces meaning we could do struct Grass : IBlock, but here boxing occurs (they turn into reference types basically), so we lose the point of having structs anyway??? 

Am I too fixated on the idea that Blocks should be a value type. Should they just be objects, and Chunk stores an array of references (bad cache locality)? Maybe they should be objects, so each block can define its own behaviour??

@DazKins @Acalc79 @JoeMcGuchan 
help me

**Comment by JamesHinshelwood** [comment]
Perhaps I'm overcomplicating and we should just have a BLOCK_TYPE enum?

However, I thought it would make sense for a block to store more than just its integer ID. For example, what texture it needs (UVs) / different textures on different faces?

**Comment by adam-kucz** [comment]
I'd just use an array of references and worry about cache locality and performance once it actually comes up as a bottleneck later. Keep in mind though that I have very little practical experience with those things.

**Comment by DazKins** [comment]
[https://github.com/DazKins/Triad/blob/master/src/com/dazkins/triad/game/world/tile/Tile.java](url)

This is how I did it in one of my projects, essentially, you can have subclasses, but only one instance exists of block type, that defines how it should be rendered and behave etc. upon construction each blocks gets but in an array with its ID as it's array position

**Comment by JamesHinshelwood** [comment]
[Fixed link](https://github.com/DazKins/Triad/blob/master/src/com/dazkins/triad/game/world/tile/Tile.java)

**Comment by JamesHinshelwood** [comment]
Ok thanks guys, I think I will go for an array of objects for now and see how it works out. If anyone has any more input though, I will leave the issue open for a bit, and feel free to chime in

**Comment by JamesHinshelwood** [comment]
Ok new idea:

The problem we are trying to solve is that we want the memory efficiency of value types (structs or primitives) so we can store block data without any level of misdirection, along with the well-structured OOP-yness of objects, so we can define our blocks in a nice, clean way. 
So how about we have our Block class:
`public abstract class Block { }`
which we extent our block types from:
`public class Grass : Block { }`
but, in the `Block` class, we store the `Id` of the block. This is the value that is stored in the chunk arrays. For example:
`{
    public byte Id;
}`
Then in Chunk we still store a `byte[,,]` of blocks, but can use some other function to convert from a `Block.Id` to a `Block` object when needed. So it is as if we are still storing 'pointers' to blocks in this array, but the 'pointers' are only 'deferenced' when they are needed to, which is hopefully rare. For example, you wouldn't need to in the rendering code, which is when these performance considerations will have the most impact.

Also, we can abstract even further and have a 
`public struct BlockId
{
    byte Id;
}`
then store a `BlockId[,,] array`, and use `BlockId` in our `Block` class. This way if we ever want to, for example, add a facing direction to each (or certain types) or blocks, we only need to change this struct. And since the struct is a value type, the above example will still only take up 1 byte for each array element.

Let me know if any of this was explained poorly, or if there is any flaws in my thinking.
@Acalc79 @DazKins 

I think this is somewhat similar to what you were describing @DazKins

**Comment by DazKins** [comment]
Does C# have some sort of typedef that will prevent us from having to use 
`public struct BlockId { byte Id; }` ?

**Comment by JamesHinshelwood** [comment]
I think we want a struct there though. If we want to add extra information
to the index of a block,it lets us.

And in this current state there is no difference between a typedef and
struct. It is still 1 byte in memory
