### ISSUE TITLE
Weird Lighting Bug

### ISSUE THREAD

**Issue by DazKins** [LimaInc/SustainableCraft#28]
![screenshot from 2018-02-01 16-02-40](https://user-images.githubusercontent.com/3652981/35688688-a30d94c4-0769-11e8-8166-7cd4aab1166f.png)
![screenshot from 2018-02-01 16-03-58](https://user-images.githubusercontent.com/3652981/35688689-a3238af4-0769-11e8-8546-ab5f94165b74.png)
Shadows seem to appear slightly offset

**Comment by JamesHinshelwood** [comment]
It's to do with the shadow bias and shadow map resolution I think
http://docs.godotengine.org/en/latest/tutorials/3d/lights_and_shadows.html

**Comment by ianyfan** [comment]
Shadows are also in the same direction as the sun, instead of opposite.

**Comment by JamesHinshelwood** [comment]
Godot has some support I saw for dynamic skyboxes and stuff, which I think @AdamSKucz has been using for sky colour? Probably the sun position is somewhere in there, so we can change that around at some point.

**Comment by DazKins** [comment]
Perhaps it is just simpler to change the direction of the light rather than fiddle with the skybox?

**Comment by JamesHinshelwood** [comment]
Yeah I guess but I just mean we can couple the directional lights rotation, to the sun in skybox, either way round

**Comment by adam-kucz** [comment]
has anyone tried to do something about this? is the shadow bias we are using right now the optimal value?

**Comment by JamesHinshelwood** [comment]
Working on this now
