### ISSUE TITLE
Hunger goes negative

### ISSUE THREAD

**Issue by JamesHinshelwood** [LimaInc/SustainableCraft#53]
Once the bar fully empties, if you keep running around, I believe the player's hunger goes into the negative, and you will have to eat multiple food items before the bar reappears. Maybe this is intended? @DazKins

**Comment by DazKins** [comment]
Essentially I suppose when the player hunger bar gets to zero they should die I suppose, but I have fixed this now anyway in the latest player branch just in case we don't want it that way

**Comment by JamesHinshelwood** [comment]
Oh yeah forgot that should be the case

**Comment by JamesHinshelwood** [comment]
Fixed by 8769668cf09511ca6edfbe762e09bc15d7df0980
