### ISSUE TITLE
Make plants and animals die/not spawn without atmosphere

### ISSUE THREAD

**Issue by JamesHinshelwood** [LimaInc/SustainableCraft#72]

**Comment by adam-kucz** [comment]
Suggested:
- Atmosphere.GetGasProgress(GasType) gives you a reliable value between 0 and 1 for each gas, I'd use those as they won't change whatever I think up of doing in future improvements, for changing gas amounts there is Atmosphere.ChangeGasAmt(GasType, float), in general everything public in the Atmosphere class may be assumed to remain unchanged (though Pressure is not normalized yet so its typical values may change drastically)
- it would be nice if other gases, not only oxygen, were necessary, what I would do is plants need some nitrogen level (say 0.5) and consume carbon dioxide (so it cannot be 0) while producing oxygen, animals consume oxygen and produce carbon dioxide, that would add population balancing effect to the atmosphere itself

I would be happy to take care of plants and animals/atmosphere interaction if you tell me what interface I can assume for both plants and animals.
