### ISSUE TITLE
Block breaking bug / feature

### ISSUE THREAD

**Issue by adam-kucz** [LimaInc/SustainableCraft#95]
Block breaking in response to clicks happens only after all the chunks in load radius have been loaded, even if the chunk where we want to remove block from is already loaded. If I have the right idea about how chunk loading works, maybe the chunk update in response to block breaking should go at the front, not the back of the queue?

**Comment by JamesHinshelwood** [comment]
Yeah probably... there's no Queue add to front, so I guess I should just make a linkedlist
